version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend
      - aws s3 cp s3://my-laravel-api-bucket/env.dev .env
      - docker build -t $ECR_REPOSITORY:latest .
      - docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY:latest
      - echo Creating imagedefinitions.json for ECS...
      - cp $CODEBUILD_SRC_DIR/backend/imagedefinitions.json $CODEBUILD_SRC_DIR/

artifacts:
  files: imagedefinitions.json
