version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend
      - aws s3 cp s3://my-laravel-api-bucket/env.dev .env
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - docker push $ECR_REPOSITORY:latest
      - echo Creating imagedefinitions.json for ECS...
      - printf '[{"name":"my-laravel-api","imageUri":"%s"}]' $ECR_REPOSITORY:$IMAGE_TAG > imagedefinitions.json
      - echo Running Laravel migrations and seeding...
      - docker run --rm $ECR_REPOSITORY:$IMAGE_TAG php artisan migrate --force
      - docker run --rm $ECR_REPOSITORY:$IMAGE_TAG php artisan db:seed --force
artifacts:
  files: imagedefinitions.json
